// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4gYZO-QoBq6iZPDF7QcaFWyaQLNvE8wo',
    appId: '1:1015843454532:web:37c9b4d6e8c31e99208611',
    messagingSenderId: '1015843454532',
    projectId: 'superchat-786cb',
    authDomain: 'superchat-786cb.firebaseapp.com',
    storageBucket: 'superchat-786cb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7aAO87j6sJKxkgAyeX7_-fN7n2ducrSQ',
    appId: '1:1015843454532:android:6ec71344f8c292ee208611',
    messagingSenderId: '1015843454532',
    projectId: 'superchat-786cb',
    storageBucket: 'superchat-786cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsqQyu6z4QRdB2EzadOIKTuXsuivFUJ3I',
    appId: '1:1015843454532:ios:ac13d3033d90d7f4208611',
    messagingSenderId: '1015843454532',
    projectId: 'superchat-786cb',
    storageBucket: 'superchat-786cb.firebasestorage.app',
    iosBundleId: 'com.example.superchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsqQyu6z4QRdB2EzadOIKTuXsuivFUJ3I',
    appId: '1:1015843454532:ios:ac13d3033d90d7f4208611',
    messagingSenderId: '1015843454532',
    projectId: 'superchat-786cb',
    storageBucket: 'superchat-786cb.firebasestorage.app',
    iosBundleId: 'com.example.superchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4gYZO-QoBq6iZPDF7QcaFWyaQLNvE8wo',
    appId: '1:1015843454532:web:94aa5e322cc92dce208611',
    messagingSenderId: '1015843454532',
    projectId: 'superchat-786cb',
    authDomain: 'superchat-786cb.firebaseapp.com',
    storageBucket: 'superchat-786cb.firebasestorage.app',
  );
}
